### ISSUE TITLE
recoverable_sign of ECDSA

### ISSUE THREAD

**Issue by hyerim-kim** [Yubico/python-yubihsm#1]
Hello, 

I wonder you have any plan to support recoverable_sign of ECDA.
(Actually, I need the recoverable_sign function. TT)

Thank you.

**Comment by dainnilsson** [comment]
Can you elaborate on this a bit? What exactly do you mean by recovery_sign? What is your use-case for this?

**Comment by hyerim-kim** [comment]
Thank you for your reply !

I used the secp256k1 curve and secp256k1.PrivateKey.ecdsa_sign_recoverable() to signing.(You can check the [API](https://github.com/ludbb/secp256k1-py/blob/master/README.md#api) of ecdsa_sign_recoverable().)
And I used the recoverable signature to verify some data after signing.
I'll assign feature of signing to YubiHSM2, that's why I need recoverable_sign() on YubiHSM2.

I think this message couldn't be enough to explain my situation.
If you need more information, tell me again. 

Thank you.

**Comment by dainnilsson** [comment]
I'm not familiar with that specific implementation and it isn't clear from the API what that method is actually doing, mathematically.

What I _think_ you might be after is what is described in the accepted answer in this post: https://bitcoin.stackexchange.com/questions/38351/ecdsa-v-r-s-what-is-v

If this is correct, then this is not something that I see us adding to this library, but you should be able to implement it yourself on top of the standard sign functionality, by testing the 4 possible values of v until you find the correct one.
