### ISSUE TITLE
Use of deprecated cryptography.utils.int_from_bytes

### ISSUE THREAD

**Issue by g-psantos** [Yubico/python-yubihsm#18]
The cryptography.io package [deprecated](https://github.com/pyca/cryptography/commit/5528a3182fdd6ed1c44c126d451a87bcf39e79de) the `utils.int_from_bytes` function in December 2020.

Executing Python scripts that rely on the YubiHSM package now triggers the following warning:

```
.../site-packages/yubihsm/objects.py:30: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_to_bytes, int_from_bytes
```

Python version: 3.7.10
YubiHSM package version: 2.0.1
Cryptography package version: 3.4.6

Would it be possible to release a fix to the YubiHSM package that addresses this issue?

**Comment by dainnilsson** [comment]
We have this and a few other things that need to be addressed. I don't have a scheduled date for a new release, but I hope we can get one out fairly soon!

**Comment by dainnilsson** [comment]
python-yubihsm 2.1.0 is now released, sorry for the delay!
