### ISSUE TITLE
Connect to YubiHsm over https with certificate

### ISSUE THREAD

**Issue by JohannesHaag** [Yubico/python-yubihsm#24]
I am not sure, if I missed something until now, but I cannot find a solution for my use case until now.
I have a yubihsm-connector running with given certificate and key files. With the python-yubihsm library I want to connect to the yubihsm-connector over https. How can I tell the yubihsm connection of session to trust the certificate of the yubihsm-connector? Is this even possible with the python library?

**Comment by dainnilsson** [comment]
It is currently possible, but isn't as simple as it should be (it should be made easier, for sure). The http backend uses the `requests` library.

You can either make sure `requests` uses a CA bundle that contains your certificate globally by setting the `REQUESTS_CA_BUNDLE` environment variable (see https://stackoverflow.com/questions/42982143/python-requests-how-to-use-system-ca-certificates-debian-ubuntu for more details).

Or you can access the ´requests.Session´ object and explicitly set `verify` to point to a different file. This will require accessing a private member of the HttpBackend, and may stop working in future versions of this library:
`hsm._backend._session.verify = "/path/to/certfile"`. This is described here: https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

**Comment by JohannesHaag** [comment]
Hi Dain. Thanks for the very quick response. Yes, that is what I already feared :) In my environment I cannot use a CA Bundle. For the second solution, is there a way without modifying the python-yubihsm library? Because that is what I now already did for testing. But it would be nicer, if I can do it from the outside, I just don't see a way for that.
What I did today, was to add a parameter ca to the HubiHsm.connect() function, pass that to get_backend() and from there forward to the constructor of HttpBackend, where I then set self._session.verify = ca.

**Comment by dainnilsson** [comment]
You could initialize the backend separately, and then pass it to the YubiHsm constructor:

```
backend = HttpBackend(url)
backend._session.verify = ca
hsm = YubiHsm(backend)
```
Or, you could call YubiHsm.connect as usual, and set verify immediately after:
```
hsm = YubiHsm.connect(url)
hsm._backend._session.veridy = ca
```
Both require accessing private members, but do not require modifying the library.

**Comment by JohannesHaag** [comment]
That works perfectly thanks, then we do not have to use a modified library. Thank you very much!
