### ISSUE TITLE
`send_secure_cmd` without a session

### ISSUE THREAD

**Issue by jschlyter** [Yubico/python-yubihsm#25]
Using `send_secure_cmd` without a session results in a `struct.error` exception (since `_secure_transceive`  is trying to pack `None` into a structure). Shouldn't that result in a `YubiHsmError`?

**Comment by elibon99** [comment]
Sorry for the delayed response. In the current version (2.3.1) you should not be able to use `send_secure_cmd` without an authenticated session.
