### ISSUE TITLE
Bad handling of origin

### ISSUE THREAD

**Issue by megahallon** [Yubico/python-yubihsm#3]
Hi, please do a new release to pypi with the fixed ORIGIN class.

**Comment by megahallon** [comment]
It seems this bug is only in the pypi (https://pypi.org/project/yubihsm) release, on gitlab ORIGIN seems correct but in the pypi tarball ORIGIN is an IntEnum.

**Comment by dainnilsson** [comment]
Missed closing this when 2.0.1 was released.
