### ISSUE TITLE
Cryptography 38 fails

### ISSUE THREAD

**Issue by jschlyter** [Yubico/python-yubihsm#31]
Running v2.1.0 with `cryptography>=38` does not work: `AttributeError: module 'cryptography.utils' has no attribute 'register_interface'`

Perhaps a release 2.1.1 with a dependency fix, `cryptography>=1.8,>=38`, is a wise choice at this time?

**Comment by dainnilsson** [comment]
Thanks for the report! But do you mean `cryptography>=1.8,<38`?

**Comment by jschlyter** [comment]
> Thanks for the report! But do you mean `cryptography>=1.8,<38`?

Yes, sorry.

**Comment by dainnilsson** [comment]
2.1.1 has now been released!
