### ISSUE TITLE
Authentication of audit log entries

### ISSUE THREAD

**Issue by g-psantos** [Yubico/python-yubihsm#36]
_My apologies in advance for posting this question to this project. I was not sure how to reach YubiHSM developers; happy to post or email elsewhere if there is a more appropriate forum._

We're developing a system service to periodically poll a YubiHSM for audit log entries, extract them to a log file, and clear the HSM's audit log buffer. The service leverages `python-yubihsm` to interact with the YubiHSM Connector, but the question isn't really about the Python module.

When we retrieve the log data, as long as there is a "last known-good" entry that we pass on to `get_log_entries()`, the method will verify the _integrity_ of the log data and raise an exception if, for whatever reason, the log entries on the HSM cannot be reconciled with the last known-good entry (e.g., someone cleared the log buffer while the service wasn't watching, or someone tampered with the last known-good entry data). Further, because sessions between the auditor service and the HSM are [end-to-end encrypted](https://developers.yubico.com/YubiHSM2/Concepts/Session.html), data integrity _and_ authenticity can be ensured at that level (provided the authentication secret remains... secret).

The problem arises when other components further upstream need to verify that the audit log data is authentic. In our case, the log entries extracted by the auditor service get forwarded to a central logging service, from where security alerting can be configured and investigations undertaken. However, the central logging service lacks a mechanism for verifying the _authenticity_ of the log entries it receives.

An attacker impersonating or otherwise compromising the auditor service could therefore easily tamper with the logs without anyone being the wiser: all it takes is knowing what the last known-good entry was, creating an arbitrary new entry, and calculating the digest of the arbitrary new entry together with the digest of the last known-good entry.

In other platforms, this is typically addressed through a combination of signing and HSM-issued heartbeat log entries. The signing is pretty obvious -- an asymmetric key pair stored in the HSM is used to sign log entries, either individually or in batches, and the corresponding public key used to verify those entries/batches. The HSM-issued heartbeats can be used to trip up an attacker "blackholing" the logging service to avoid detection -- if no heartbeat entries are received within a predefined timespan, alarms go off.

I haven't found anything in the documentation to suggest that the YubiHSM supports these capabilities, so I'm wondering (1) if others have encountered these risks and, if so, how they were mitigated; and (2) if Yubico would consider implementing these capabilities, possibly in the next version of the YubiHSM.

**Comment by sahmadyubico** [comment]
Hi there! YubiHSM 2 as of now does have the capabilities you have mentioned in your question. However, the logs are hash-chained. That means that every log's hash is computed by including the hash of the previous log entry. This ensures that no logs can be added or removed from the chain. Furthermore, if the server has the first entry, it can verify the whole chain and verify that the chain is unbroken. 

I hope this answers your question.

**Comment by g-psantos** [comment]
Hi @sahmadyubico, thanks for pitching in. As mentioned above (and I realize it's a long text), the problem is that a party without direct access to the YubiHSM has no way to verify that the "chain" of hashes they're receiving is legitimate.

To illustrate this point, consider `H := SHA256` and the initial random seed to be `12345`. For simplicity, the hash of each "log entry" is simply the SHA-256 hash of the log entry's content concatenated with the hash of the previous log entry (or the random seed in the case of the first entry).

**Original Log:**

| Sequence | Log Entry | H(Log Entry + H(-1)) |
| --- | --- | --- |
| 1 | HSM initialized | `H(HSM initialized + Random=12345) = d5af3d15...` |
| 2 | Authentication successful | `H(Authentication successful + d5af3d15...) = 8293be8c...` |
| 3 | RSA signing | `H(RSA signing + 8293be8c...) = ea860a39...` |

**Tampered Log:**

| Sequence | Log Entry | H(Log Entry + H(-1)) |
| --- | --- | --- |
| 1 | HSM initialized | `H(HSM initialized + Random=12345) = d5af3d15...` |
| 2 | Authentication successful | `H(Authentication successful + d5af3d15...) = 8293be8c...` |
| 3' | Echo | `H(Echo + 8293be8c...) = 0a75e7ba...` |

As you can see, a party that is present at HSM initialization and knows the first hash, but then receives logs through an intermediary, cannot tell that the logs were tampered with: the intermediary can simply compute the hash for the forged entries and keep on going with the forged log entry chain.

Contrast this with a case where the YubiHSM itself is _signing_ log entries with an _asymmetric key_: any party that is present at initialization and has the log signing public key can verify the authenticity and integrity of the logs.

**Comment by baodvu** [comment]
I just want to comment that this ask is also critical for our company. As of now, YubiHSM's audit logging offers a false sense of security as the logs can't be verified by itself. Can you have the yubihsm sign the audit logs with its own built-in private key? It would also be nice if it has an attestation certificate that chains up to Yubico.

**Comment by elibon99** [comment]
I appreciate your patience and apologize for the delayed response. Regarding your inquiry about signing arbitrary log entries with the YubiHSM, unfortunately, this specific capability is currently not supported. If there are any changes in this regard we will implement support for it. At this point, I am closing this issue. Should you have any further questions or concerns, please feel free to reach out or re-open the issue.
