### ISSUE TITLE
When will version 3.x be released?

### ISSUE THREAD

**Issue by baodvu** [Yubico/python-yubihsm#37]
The cryptography library 37.x has some CVE risks so we want to move away from using an outdated dependency.

**Comment by dainnilsson** [comment]
Apologies for the late response. We currently don't have a release date for version 3.0, but it looks like we'll have some more time to work on it soon. In the meantime, we've just released 2.1.3 to address the compatibility with later versions of Cryptography.

**Comment by baodvu** [comment]
Thanks for the minor version release. It works with cryptography 41 so I'm good here.
