### ISSUE TITLE
[question] Support for AES-CBC encryption?

### ISSUE THREAD

**Issue by bkranendonk** [Yubico/python-yubihsm#38]
Hi there,

I'm looking for the use of CBC AES encryption using this Python module on my YubiHSM 2 FIPS. How can I achieve this?

**Comment by elibon99** [comment]
Apologies for the late response. We are currently working on adding support for AES encryption/decryption in both ECB and CBC modes. The core functionality has already been merged into the `master` branch, so if you're interested, you can test it out. Alternatively, this support will be included in the upcoming major release scheduled for later this year.

**Comment by bkranendonk** [comment]
That's great. I think this will only work with the regular YubiHSMs since the FIPS HSMs come with FW v2.2

I believe AES CBC is supported since FW v2.4, can you confirm this?

**Comment by elibon99** [comment]
> That's great. I think this will only work with the regular YubiHSMs since the FIPS HSMs come with FW v2.2

Yes, you're correct. Currently, the YubiHSM 2 FIPS version comes with FW v2.2, so AES is not supported there. 

> I believe AES CBC is supported since FW v2.4, can you confirm this?

AES CBC and ECB is available with FW v2.3.
