### ISSUE TITLE
When does the exception message of "Incorrect MAC" be raised ?

### ISSUE THREAD

**Issue by hyerim-kim** [Yubico/python-yubihsm#4]
Hello, 

When do I meet the exception message of 'Incorrect MAC'?

I meet the message pretty frequently. But there is no difference to work step between normal case and unnormal case.
Here is the unnormal case log:
1. python application log
```
0401 14:10:25,587 82032 123145475153920 hx732e57 icon_dex DEBUG connectionpool.py(393) http://127.0.0.1:12345 "POST /connector/api HTTP/1.1" 200 4
0401 14:10:25,590 82032 123145475153920 hx732e57 icon_dex ERROR timer_service.py(213) Task exception was never retrieved
future: <Task finished coro=<ConsensusSiever.consensus() done, defined at "/Users/user/peer/consensus_siever.py:46> exception=YubiHsmInvalidResponseError('Incorrect MAC',)>

Traceback (most recent call last):
  File "/Users/user/peer/consensus_siever.py", line 114, in consensus
    candidate_block = block_builder.build()
  File "/Users/user/blockchain/blocks/v0_3/block_builder.py", line 69, in build
    self.sign()
  File "/Users/user/blockchain/blocks/v0_3/block_builder.py", line 213, in sign
    self.signature = self._sign_in_hsm() if conf.HSM_ENABLE_USE else self._sign()
  File "/Users/user/blockchain/blocks/v0_3/block_builder.py", line 226, in _sign_in_hsm
    HsmHelper().open()
  File "/Users/user/tools/hsm_helper.py", line 41, in open
    self.close()
  File "/Users/user/tools/hsm_helper.py", line 55, in close
    self.__session.close()
  File "/Users/user/lib/python3.6/site-packages/yubihsm/core.py", line 335, in close
    self.send_secure_cmd(COMMAND.CLOSE_SESSION)
  File "/Users/user/lib/python3.6/site-packages/yubihsm/core.py", line 325, in send_secure_cmd
    return _unpad_resp(self._secure_transceive(msg), cmd)
  File "/Users/user/lib/python3.6/site-packages/yubihsm/core.py", line 294, in _secure_transceive
    raise YubiHsmInvalidResponseError('Incorrect MAC')
yubihsm.exceptions.YubiHsmInvalidResponseError: Incorrect MAC
```

2. yubihsm-shell log
```
DEBU[455455] usb device already open                       Correlation-ID=7c075602-8d40-00cb-a06b-a853ae62138e
DEBU[455455] usb endpoint write                            Correlation-ID=7c075602-8d40-00cb-a06b-a853ae62138e buf="[5 0 25 0 170 148 247 140 3 236 166 208 205 78 77 115 194 37 99 114 22 136 132 147 176 212 159 98]" err="<nil>" len=28 n=28
DEBU[455455] usb endpoint read                             Correlation-ID=7c075602-8d40-00cb-a06b-a853ae62138e buf="[127 0 1 3]" err="<nil>" len=4 n=4
INFO[455455] handled request                               Content-Length=28 Content-Type=application/octet-stream Method=POST RemoteAddr="127.0.0.1:53894" StatusCode=200 URI=/connector/api User-Agent=python-requests/2.20.0 X-Real-IP=127.0.0.1 X-Request-ID=7c075602-8d40-00cb-a06b-a853ae62138e latency="514.971µs"
```
Although the exception case occurs, it's recovered after some time.
I wonder if there is any time the device needs time to rest.

Please let me know when does the exception message is raised.

Thank you.

**Comment by megahallon** [comment]
As the maintainer seems to be MIA I will say something on this. I have also seen that the session is shutdown by the HSM after some time, at this point all access will fail with the "Incorrect MAC" error (including "close session" call). My fix was to store the password inside my service and at each call check for this error and create a new session if needed.

**Comment by hyerim-kim** [comment]
Thank you for your reply :)

I resolved it almost like your reply.
I implement to open a new session every time before the function is used I mentioned above and to close the session immediately after the function is used.
But I'm not sure it is a correct way and I guess it is inefficient.

**Comment by dainnilsson** [comment]
The 2.0.1 release improves the error handling around this and results in a more accurate error message. For sessions that are expired (which happens after 30 seconds of inactivity) you will now get an `INVALID_SESSION` error instead. You can either use a new session each time you need to interact with the HSM, or catch the error and re-establish the session as needed, depending on your use-case.
