### ISSUE TITLE
Failure to open YubiHSM 2 by serial number with two or more devices

### ISSUE THREAD

**Issue by wecode11** [Yubico/python-yubihsm#52]
# Problem
Using multiple YubiHSM 2 on a single host requires knowledge of the underlying USB device order in the application code. This affects the ability to perform provisioning of keying material between devices when using _yhusb://serial=_ to open a specific YubiHSM 2 device.

Identified in python-yubihsm 2.1.3 using Python 3.11 on a Window 11 platform.

## Cause
An open USB device will not provide the device serial number which will cause a ValueError exception in _usb.util_ to be raised. This will in turn abort the search for a device with a matching serial number.

## Expected Behavior
If the serial number of a YubiHSM 2 cannot be retrieved from a USB device, the device should be ignored. This allow the search for a device with a matching serial number to continue with the next USB device in the list provided by _usb.core.find_. It is acceptable that the  _YubiHsmConnectionError("No YubiHSM found.")_ exception is raised if the specified serial number is already open and can therefore not be identified.

# Solution
Add a _try - except_ around the test of the serial number in [yubihsm/backends/usb.py](https://github.com/Yubico/python-yubihsm/blob/master/yubihsm/backends/usb.py) line 38.

        for device in usb.core.find(
            find_all=True, idVendor=YUBIHSM_VID, idProduct=YUBIHSM_PID
        ):
            try:
                if serial is None or int(device.serial_number) == serial:
                    break
            except Exception:
                pass
        else:
            raise YubiHsmConnectionError("No YubiHSM found.")

**Comment by elibon99** [comment]
Thank you for submitting this issue! After investigating your problem, we've determined that it is specific to Windows 11 platforms when parsing the device serial number. PR #53 addresses this issue with a workaround that will be included in the upcoming major version (3.0.0), that we hope to release in the near future.
