### ISSUE TITLE
Missing 'py.typed' for type checkers to be in compliance with PEP 561

### ISSUE THREAD

**Issue by GalLadislav** [Yubico/python-yubihsm#58]
First, thank you for adding type hints in the newest version (3.0.0). Unfortunately, to be properly usable with type checkers like Mypy, it is missing 'py.typed' file to give a type checker information about it being inline typed. ([PEP 561](https://peps.python.org/pep-0561/)).

Adding 'py.typed' file would be very appreciated.

**Comment by elibon99** [comment]
Sorry for the late response! We will add this in a future release.

**Comment by elibon99** [comment]
Closing since `py.typed` now has been added in our most recent release.
