### ISSUE TITLE
Use ed25519 from cryptography.io

### ISSUE THREAD

**Issue by paulhovey** [Yubico/python-yubihsm#6]
Cryptography.io has support for ed25519 algorithm as of [PR4114](https://github.com/pyca/cryptography/pull/4114) .  The comment at [eddsa.py#L18](https://github.com/Yubico/python-yubihsm/blob/master/yubihsm/eddsa.py#L18) makes it seem like it is desired to use it at some point?  Is there any reason not to use the cryptography implementation?

**Comment by dainnilsson** [comment]
No reason other than not having gotten around to it until now. This is now fixed on master.
