### ISSUE TITLE
Deleting an object after creating

### ISSUE THREAD

**Issue by evso9816** [Yubico/python-yubihsm#7]
I have a program that allows me to create a session, private and public keys, generate a random number. But, because I am using a loop, the HSM2 gets fill up (0x07).
I would love to delete whatever gets store on the HSM2.
Here is what I did:
        #self.priv_key.delete()
        #self.pub_key.delete()
        **self.session.delete()   ------------> 'AuthSession' object has no attribute 'delete'**
        #self.session2.close()
        self.hsm.close()
        #self.hsm.reset()
        #self.session.reset_device
What can I do to delete immediatly: session, private key, public key, or authentication key, random number or any object generated or created?
Additionally, when I close a session, does it mean that the store contents are saved or get deleted?

Thanks all for your advice!

**Comment by dainnilsson** [comment]
A session isn't stored as an object, and thus cannot be deleted. Closing the session when you're done with it is sufficient. Closing a session will not delete any objects created during the session.

All objects that are created and stored on the YubiHSM can be deleted by using the .delete() method. Private and public keys are stored and operated on as a pair.
